#
# buildspec.yml
#

version: 0.2

env:
  variables:
    deploy_bucket: api-gateway-lambda-deploy
    deploy_payload: deployment.zip

phases:
  install:
    runtime-versions:
      nodejs: 20
#    commands:

  pre_build:
    commands:
      - BUILD_VERSION=$(date --date="@$(echo ${CODEBUILD_START_TIME} | cut -c1-10)" +"%Y%m%d%H%M%S")
      - COMMIT_TAG=gitcommit-${CODEBUILD_RESOLVED_SOURCE_VERSION}

  build:
    commands:
      #
      # build the assets
      #
      # libcal-Hours function
      - cd ${CODEBUILD_SRC_DIR}/libcal-Hours
      - npm install
      - zip -r ${deploy_payload} .
      #
      # mkrsp-libauth-3dprinter function
      - cd ${CODEBUILD_SRC_DIR}/mkrsp-libauth-3dprinter
      - npm install
      - zip -r ${deploy_payload} .
      #
      # mkrsp-quiz-3dprinter function
      - cd ${CODEBUILD_SRC_DIR}/mkrsp-quiz-3dprinter
      - npm install
      - zip -r ${deploy_payload} .
      #
      # purchaserequestsubmit function
      - cd ${CODEBUILD_SRC_DIR}/purchaserequestsubmit
      - npm install
      - zip -r ${deploy_payload} .
      #
      # scclassinstructionsubmit function
      - cd ${CODEBUILD_SRC_DIR}/scclassinstructionsubmit
      - npm install
      - zip -r ${deploy_payload} .
      #
      # spaceeventsjson function
      - cd ${CODEBUILD_SRC_DIR}/spaceeventsjson
      - npm install
      - zip -r ${deploy_payload} .
      #
      # staffpurchasesubmit function
      - cd ${CODEBUILD_SRC_DIR}/staffpurchasesubmit
      - npm install
      - zip -r ${deploy_payload} .
      #
      # totaladvisinglibcalspaceevents function
      - cd ${CODEBUILD_SRC_DIR}/totaladvisinglibcalspaceevents
      - npm install
      - zip -r ${deploy_payload} .
      #
      # video-clip-form-email function
      - cd ${CODEBUILD_SRC_DIR}/video-clip-form-email
      - npm install
      - zip -r ${deploy_payload} .
      #
      # copy to the results bucket
      #
      #
      # libcal-Hours function
      - aws s3 cp ${CODEBUILD_SRC_DIR}/libcal-Hours/${deploy_payload} s3://${deploy_bucket}/${BUILD_VERSION}/libcal-Hours/${deploy_payload} --quiet
      #
      # mkrsp-libauth-3dprinter function
      - aws s3 cp ${CODEBUILD_SRC_DIR}/mkrsp-libauth-3dprinter/${deploy_payload} s3://${deploy_bucket}/${BUILD_VERSION}/mkrsp-libauth-3dprinter/${deploy_payload} --quiet
      #
      # mkrsp-quiz-3dprinter function
      - aws s3 cp ${CODEBUILD_SRC_DIR}/mkrsp-quiz-3dprinter/${deploy_payload} s3://${deploy_bucket}/${BUILD_VERSION}/mkrsp-quiz-3dprinter/${deploy_payload} --quiet
      #
      # purchaserequestsubmit function
      - aws s3 cp ${CODEBUILD_SRC_DIR}/purchaserequestsubmit/${deploy_payload} s3://${deploy_bucket}/${BUILD_VERSION}/purchaserequestsubmit/${deploy_payload} --quiet
      #
      # scclassinstructionsubmit function
      - aws s3 cp ${CODEBUILD_SRC_DIR}/scclassinstructionsubmit/${deploy_payload} s3://${deploy_bucket}/${BUILD_VERSION}/scclassinstructionsubmit/${deploy_payload} --quiet
      #
      # spaceeventsjson function
      - aws s3 cp ${CODEBUILD_SRC_DIR}/spaceeventsjson/${deploy_payload} s3://${deploy_bucket}/${BUILD_VERSION}/spaceeventsjson/${deploy_payload} --quiet
      #
      # staffpurchasesubmit function
      - aws s3 cp ${CODEBUILD_SRC_DIR}/staffpurchasesubmit/${deploy_payload} s3://${deploy_bucket}/${BUILD_VERSION}/staffpurchasesubmit/${deploy_payload} --quiet
      #
      # totaladvisinglibcalspaceevents function
      - aws s3 cp ${CODEBUILD_SRC_DIR}/totaladvisinglibcalspaceevents/${deploy_payload} s3://${deploy_bucket}/${BUILD_VERSION}/totaladvisinglibcalspaceevents/${deploy_payload} --quiet
      #
      # video-clip-form-email function
      - aws s3 cp ${CODEBUILD_SRC_DIR}/video-clip-form-email/${deploy_payload} s3://${deploy_bucket}/${BUILD_VERSION}/video-clip-form-email/${deploy_payload} --quiet
      #
      # create the git commit tag file
      #
      - touch ${CODEBUILD_SRC_DIR}/${COMMIT_TAG}.git
      - aws s3 cp ${CODEBUILD_SRC_DIR}/${COMMIT_TAG}.git s3://${deploy_bucket}/${BUILD_VERSION}/${COMMIT_TAG}.git --quiet
      #
      # make the latest folder
      #
      - aws s3 sync s3://${deploy_bucket}/${BUILD_VERSION} s3://${deploy_bucket}/latest --delete --quiet
      #
      # update the latest tag
      #
      - aws --region=$AWS_REGION ssm put-parameter --name /lambdas/${deploy_bucket}/latest --value ${BUILD_VERSION} --type String --overwrite

#  post_build:
#    commands:

#
# end of file
#
